name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code
      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build the website docker image
      with:
        image: nexuswaveai/nexuswaveai_images
        tags: website
        registry: docker.io
        dockerfile: Dockerfile
        directory: ./
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
